"""
Autonomous DevOps Agent Configuration

All configurable parameters in one place for easy reuse across projects.
"""
from dataclasses import dataclass
from typing import Dict, Optional

@dataclass
class ModelConfig:
    """LLM model configuration"""
    # Model names
    SONNET_MODEL = "claude-sonnet-4-5-20250929"
    OPUS_MODEL = "claude-opus-4-5-20250820"

    # Attempt thresholds for model switching
    SONNET_MAX_ATTEMPTS = 4  # Use Sonnet for attempts 1-4
    OPUS_MAX_ATTEMPTS = 6    # Use Opus for attempts 5-6
    ESCALATION_THRESHOLD = 7  # Escalate to human after attempt 6

    # Model parameters
    MAX_TOKENS = 8192
    TEMPERATURE = 0.0  # Deterministic for consistency

    def get_model_for_attempt(self, attempt: int) -> str:
        """
        Get appropriate model based on attempt number

        Args:
            attempt: Current attempt number (1-indexed)

        Returns:
            Model name to use
        """
        if attempt <= self.SONNET_MAX_ATTEMPTS:
            return self.SONNET_MODEL
        elif attempt <= self.OPUS_MAX_ATTEMPTS:
            return self.OPUS_MODEL
        else:
            raise ValueError(f"Attempt {attempt} exceeds max attempts {self.OPUS_MAX_ATTEMPTS}")

    def should_escalate(self, attempt: int) -> bool:
        """
        Check if we should escalate to human

        Args:
            attempt: Current attempt number (1-indexed)

        Returns:
            True if should escalate to human
        """
        return attempt >= self.ESCALATION_THRESHOLD


@dataclass
class GitConfig:
    """Git and GitHub configuration"""
    # Branch naming
    BRANCH_PREFIX = "autonomous-fix"
    BRANCH_FORMAT = "{prefix}-{fix_id}/attempt-{attempt}"

    # Labels
    LABEL_PREFIX = "autonomous-fix"
    LABEL_ATTEMPT_FORMAT = "attempt-{attempt}"
    LABEL_PLATFORM_FORMAT = "platform-{platform}"
    LABEL_HIGH_CONFIDENCE = "high-confidence"
    LABEL_NEEDS_HUMAN = "needs-human-attention"

    # PR configuration
    PR_TITLE_FORMAT = "🤖 Auto-Fix: {description}"
    PR_BODY_TEMPLATE = """## 🤖 Autonomous DevOps Agent

**Fix ID:** {fix_id}
**Attempt:** {attempt} of {max_attempts}
**Model Used:** {model}
**Confidence:** {confidence:.2f}

{previous_attempts_section}

## 🔍 Root Cause

{root_cause}

## 🔧 Fix Applied

{fix_description}

**Reasoning:**
{reasoning}

## 📚 Skill Updates

{skill_updates_section}

## 📁 Files Changed

{files_changed}

---
Generated by Autonomous DevOps Agent
Run: {run_id}
"""

    def format_branch_name(self, fix_id: str, attempt: int) -> str:
        """Format branch name"""
        return self.BRANCH_FORMAT.format(
            prefix=self.BRANCH_PREFIX,
            fix_id=fix_id,
            attempt=attempt
        )

    def format_labels(self, fix_id: str, attempt: int, platform: str,
                     high_confidence: bool = False) -> list[str]:
        """Format PR/issue labels"""
        labels = [
            f"{self.LABEL_PREFIX}-{fix_id}",
            self.LABEL_ATTEMPT_FORMAT.format(attempt=attempt),
            self.LABEL_PLATFORM_FORMAT.format(platform=platform)
        ]

        if high_confidence:
            labels.append(self.LABEL_HIGH_CONFIDENCE)

        return labels


@dataclass
class SkillConfig:
    """Skill knowledge configuration"""
    # Skill file paths (relative to skills directory)
    MAIN_SKILL = "SKILL.md"
    TROUBLESHOOTING_TEMPLATE = "troubleshooting.{platform}.md"

    # Pattern confidence thresholds
    HIGH_CONFIDENCE_THRESHOLD = 0.85
    MEDIUM_CONFIDENCE_THRESHOLD = 0.60
    LOW_CONFIDENCE_THRESHOLD = 0.0

    # Skill update settings
    AUTO_UPDATE_SKILL = True
    INCLUDE_SKILL_IN_PR = True

    def get_confidence_level(self, confidence: float) -> str:
        """Get confidence level label"""
        if confidence >= self.HIGH_CONFIDENCE_THRESHOLD:
            return "HIGH"
        elif confidence >= self.MEDIUM_CONFIDENCE_THRESHOLD:
            return "MEDIUM"
        else:
            return "LOW"


@dataclass
class AgentConfig:
    """Main agent configuration"""
    model: ModelConfig
    git: GitConfig
    skill: SkillConfig

    # Agent behavior
    ENABLE_AUTO_FIX = True
    ENABLE_PR_CREATION = True
    ENABLE_SKILL_UPDATES = True

    # Logging
    VERBOSE = True
    LOG_FILE = "agent.log"

    @classmethod
    def default(cls) -> 'AgentConfig':
        """Create default configuration"""
        return cls(
            model=ModelConfig(),
            git=GitConfig(),
            skill=SkillConfig()
        )

    def to_dict(self) -> Dict:
        """Convert to dictionary for serialization"""
        return {
            'model': {
                'sonnet_model': self.model.SONNET_MODEL,
                'opus_model': self.model.OPUS_MODEL,
                'sonnet_max_attempts': self.model.SONNET_MAX_ATTEMPTS,
                'opus_max_attempts': self.model.OPUS_MAX_ATTEMPTS,
                'escalation_threshold': self.model.ESCALATION_THRESHOLD
            },
            'git': {
                'branch_prefix': self.git.BRANCH_PREFIX,
                'label_prefix': self.git.LABEL_PREFIX
            },
            'skill': {
                'high_confidence_threshold': self.skill.HIGH_CONFIDENCE_THRESHOLD,
                'medium_confidence_threshold': self.skill.MEDIUM_CONFIDENCE_THRESHOLD,
                'auto_update_skill': self.skill.AUTO_UPDATE_SKILL
            },
            'agent': {
                'enable_auto_fix': self.ENABLE_AUTO_FIX,
                'enable_pr_creation': self.ENABLE_PR_CREATION,
                'enable_skill_updates': self.ENABLE_SKILL_UPDATES
            }
        }


# Global default configuration instance
DEFAULT_CONFIG = AgentConfig.default()
